[server]
http_port = "8000"
log_level = "error"

[app]
run_updator = true
develop = false
db_connection = ""

[loggly]
client_id = ""

[twitter]
consumer_key = ""
consumer_secret = ""
access_token = ""
access_token_secret = ""

[foursquare]
client_id = ""
client_secret = ""
