[sfbt]
cssFolder = "static/css"
targetCssFile = "static/site.css"
jsFolder = "static/js"
targetJsFile = "static/site.js"

[server]
http_port = "8000"
log_level = "error"
session_secret = ""

[app]
run_updator = true
develop = false

[loggly]
client_id = ""