package main

import (
	"net/http"
	"strconv"

	"wanderinglunch/model"

	"github.com/zenazn/goji/web"
)

/**
 * @api {get} /subs List Substitutions
 * @apiName GetSubs
 * @apiDescription To get an array of all the substitutions in the database
 * @apiVersion 1.0.0
 * @apiGroup Substitutions
 * @apiExample {GET} Example usage:
 *     http://api.wanderinglunch.com/subs
 * @apiSuccessExample {json} Success-Response:
 *  [
 *    {
 *      "id": 1,
 *      "regex": "\.",
 *      "replacement": " "
 *    },
 *    {
 *      "id": 2,
 *      "regex": "-",
 *      "replacement": " "
 *    }
 *  ]
 */
func substitutions(c web.C, w http.ResponseWriter, r *http.Request) {
	renderer.JSON(w, http.StatusOK, model.GetSubs())
}

/**
 * @api {get} /subs/:id Get Substitution
 * @apiName GetSub
 * @apiDescription Get a substition by id
 * @apiVersion 1.0.0
 * @apiParam {Number} id Autogenerated id of the substition
 * @apiGroup Substitutions
 * @apiExample {GET} Example usage:
 *     http://api.wanderinglunch.com/subs/1
 * @apiSuccessExample {json} Success-Response:
 *  {
 *    "id": 1,
 *    "regex": "\.",
 *    "replacement": " "
 *  }
 */
func subsitution(c web.C, w http.ResponseWriter, r *http.Request) {
	var ae apiErrors
	sub := model.GetSub(c.URLParams["id"])
	if sub.ID == 0 {
		ae.Errors = append(ae.Errors, apiError{Message: "No substitution with that id found"})
		renderer.JSON(w, http.StatusNotFound, ae)
		return
	}
	renderer.JSON(w, http.StatusOK, sub)
}

/**
 * @api {post} /subs Create a new substitution
 * @apiName NewSub
 * @apiDescription Save a new substition
 * @apiVersion 1.0.0
 * @apiUse Sub
 * @apiGroup Substitutions
 */
func subInsert(c web.C, w http.ResponseWriter, r *http.Request) {
	err := r.ParseForm()
	if err != nil {
		renderer.JSON(w, http.StatusInternalServerError, nil)
	}
	s := model.SubMarshal(r.Form)
	if model.AddSub(s) {
		renderer.JSON(w, http.StatusOK, model.GetSubByRegex(s.Regex))
		return
	}
	renderer.JSON(w, http.StatusInternalServerError, nil)
}

/**
 * @api {put} /subs/:id Update a substitution
 * @apiName UpdateSub
 * @apiDescription Update a substition
 * @apiVersion 1.0.0
 * @apiParam {Number} id Id of the sub to update
 * @apiUse Sub
 * @apiGroup Substitutions
 */
func subUpdate(c web.C, w http.ResponseWriter, r *http.Request) {
	err := r.ParseForm()
	if err != nil {
		renderer.JSON(w, http.StatusInternalServerError, nil)
	}
	s := model.SubMarshal(r.Form)
	s.ID, _ = strconv.Atoi(c.URLParams["id"])
	if model.UpdateSub(s) {
		renderer.JSON(w, http.StatusOK, model.GetSub(c.URLParams["id"]))
		return
	}
	renderer.JSON(w, http.StatusInternalServerError, nil)
}

/**
 * @api {delete} /subs/:id Delete a substitution
 * @apiName DeleteSub
 * @apiVersion 1.0.0
 * @apiParam {Number} id Id of the sub to delete
 * @apiGroup Substitutions
 */
func subDelete(c web.C, w http.ResponseWriter, r *http.Request) {
	if model.DeleteSub(c.URLParams["id"]) {
		renderer.JSON(w, http.StatusNoContent, nil)
		return
	}
	renderer.JSON(w, http.StatusInternalServerError, nil)
}
