// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Images    string
	Locations string
	Sites     string
	Spots     string
	Subs      string
	Trucks    string
	Tweets    string
	Users     string
}{
	Images:    "images",
	Locations: "locations",
	Sites:     "sites",
	Spots:     "spots",
	Subs:      "subs",
	Trucks:    "trucks",
	Tweets:    "tweets",
	Users:     "users",
}
