// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Images", testImagesUpsert)

	t.Run("Locations", testLocationsUpsert)

	t.Run("Sites", testSitesUpsert)

	t.Run("Spots", testSpotsUpsert)

	t.Run("Subs", testSubsUpsert)

	t.Run("Trucks", testTrucksUpsert)

	t.Run("Tweets", testTweetsUpsert)

	t.Run("Users", testUsersUpsert)
}
